# Data Visualization

In [1]:
import pandas as pd
import numpy as np
import os
import altair as alt
from altair_saver import save  
from pyecharts import options as opts   
from pyecharts.charts import  Timeline,Map

## Import data

In [2]:
urlemdat = 'https://github.com/Themaoyc/MDA/blob/main/Data/emdat%20heatwave.csv?raw=true'
df = pd.read_csv(urlemdat)
df

,Dis No,Year,Seq,Glide,Disaster Group,Disaster Subgroup,Disaster Type,Disaster Subtype,Disaster Subsubtype,Event Name,...,"Reconstruction Costs, Adjusted ('000 US$)",Insured Damages ('000 US$),"Insured Damages, Adjusted ('000 US$)",Total Damages ('000 US$),"Total Damages, Adjusted ('000 US$)",CPI,Adm Level,Admin1 Code,Admin2 Code,Geo Locations
0,1990-0356-MEX,1990,356,NaN,Natural,Meteorological,Extreme temperature,Heat wave,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,48.218797,NaN,NaN,NaN,NaN
1,1990-0085-FRA,1990,85,NaN,Natural,Meteorological,Extreme temperature,Heat wave,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,48.218797,NaN,NaN,NaN,NaN
2,1990-0388-KOR,1990,388,NaN,Natural,Meteorological,Extreme temperature,Heat wave,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,48.218797,NaN,NaN,NaN,NaN
3,1990-0373-USA,1990,373,NaN,Natural,Meteorological,Extreme temperature,Heat wave,NaN,NaN,...,NaN,265000.0,549578.0,NaN,NaN,48.218797,NaN,NaN,NaN,NaN
4,1991-0279-PAK,1991,279,NaN,Natural,Meteorological,Extreme temperature,Heat wave,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,50.260853,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
178,2020-0530-NLD,2020,530,NaN,Natural,Meteorological,Extreme temperature,Heat wave,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,95.512967,1,2158;2159;2160;2161;2162;2163;2164;2165;2166;2...,NaN,"Drenthe, Flevoland, Friesland, Gelderland, Gro..."
179,2021-0369-CAN,2021,369,NaN,Natural,Meteorological,Extreme temperature,Heat wave,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,100.000000,1,826,NaN,British Columbia / Colombie-Britannique (Adm1).
180,2021-0390-USA,2021,390,NaN,Natural,Meteorological,Extreme temperature,Heat wave,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,100.000000,1,3218;3226;3242;3251;3261,NaN,"California, Idaho, Nevada, Oregon, Washington ..."
181,2022-0248-IND,2022,248,NaN,Natural,Meteorological,Extreme temperature,Heat wave,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
182,2022-0248-PAK,2022,248,NaN,Natural,Meteorological,Extreme temperature,Heat wave,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Heatwave map

In [3]:
df_map =pd.DataFrame(df) 
countryname= df_map['Country']
df_map['Countryshort'] = df_map['Country']
df_map.loc[df_map['Country'] == 'United States of America (the)','Countryshort']= 'United States'
df_map.loc[df_map['Country'] == 'Netherlands (the)','Countryshort']= 'Netherlands'
df_map.loc[df_map['Country'] == 'Macedonia (the former Yugoslav Republic of)','Countryshort']= 'Macedonia'
df_map.loc[df_map['Country'] == 'Czech Republic (the)','Countryshort']= 'Czech Rep.'
df_map.loc[df_map['Country'] == 'Korea (the Republic of)','Countryshort']= 'Korea'
df_map.loc[df_map['Country'] == 'Sudan (the)','Countryshort']= 'Sudan'
df_map.loc[df_map['Country'] == "Korea (the Democratic People's Republic of)",'Countryshort']= 'Dem. Rep. Korea '
df_map.loc[df_map['Country'] == 'Bolivia (Plurinational State of)','Countryshort']= 'Bolivia'
df_map.loc[df_map['Country'] == 'Russian Federation (the)','Countryshort']= 'Russia'
df_map.loc[df_map['Country'] == 'United Kingdom of Great Britain and Northern Ireland (the)','Countryshort']= 'United Kingdom'
df_map.loc[df_map['Country'] == 'Bosnia and Herzegovina','Countryshort']= 'Bosnia and Herz.'

#calculate the times of heatwave in a country in the same year


df_map['cy']=df_map['Countryshort']+df_map['Year'].apply(str)
times=df_map["cy"].value_counts().to_dict()

df_map['times']=1
df_map.loc[df_map['cy'] == 'Japan2015','times']= 3
df_map.loc[df_map['cy'] == 'Belgium2019 ','times']= 3
df_map.loc[df_map['cy'] == 'United Kingdom2019','times']= 2
df_map.loc[df_map['cy'] == 'Germany2019 ','times']= 2
df_map.loc[df_map['cy'] == 'United States2006 ','times']= 2
df_map.loc[df_map['cy'] == 'Australia1994 ','times']= 2
df_map.loc[df_map['cy'] == 'Japan2019 ','times']= 2
df_map.loc[df_map['cy'] == 'India2019 ','times']= 2
df_map.loc[df_map['cy'] == 'France2019 ','times']= 2
df_map

,Dis No,Year,Seq,Glide,Disaster Group,Disaster Subgroup,Disaster Type,Disaster Subtype,Disaster Subsubtype,Event Name,...,Total Damages ('000 US$),"Total Damages, Adjusted ('000 US$)",CPI,Adm Level,Admin1 Code,Admin2 Code,Geo Locations,Countryshort,cy,times
0,1990-0356-MEX,1990,356,NaN,Natural,Meteorological,Extreme temperature,Heat wave,NaN,NaN,...,NaN,NaN,48.218797,NaN,NaN,NaN,NaN,Mexico,Mexico1990,1
1,1990-0085-FRA,1990,85,NaN,Natural,Meteorological,Extreme temperature,Heat wave,NaN,NaN,...,NaN,NaN,48.218797,NaN,NaN,NaN,NaN,France,France1990,1
2,1990-0388-KOR,1990,388,NaN,Natural,Meteorological,Extreme temperature,Heat wave,NaN,NaN,...,NaN,NaN,48.218797,NaN,NaN,NaN,NaN,Korea,Korea1990,1
3,1990-0373-USA,1990,373,NaN,Natural,Meteorological,Extreme temperature,Heat wave,NaN,NaN,...,NaN,NaN,48.218797,NaN,NaN,NaN,NaN,United States,United States1990,1
4,1991-0279-PAK,1991,279,NaN,Natural,Meteorological,Extreme temperature,Heat wave,NaN,NaN,...,NaN,NaN,50.260853,NaN,NaN,NaN,NaN,Pakistan,Pakistan1991,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
178,2020-0530-NLD,2020,530,NaN,Natural,Meteorological,Extreme temperature,Heat wave,NaN,NaN,...,NaN,NaN,95.512967,1,2158;2159;2160;2161;2162;2163;2164;2165;2166;2...,NaN,"Drenthe, Flevoland, Friesland, Gelderland, Gro...",Netherlands,Netherlands2020,1
179,2021-0369-CAN,2021,369,NaN,Natural,Meteorological,Extreme temperature,Heat wave,NaN,NaN,...,NaN,NaN,100.000000,1,826,NaN,British Columbia / Colombie-Britannique (Adm1).,Canada,Canada2021,1
180,2021-0390-USA,2021,390,NaN,Natural,Meteorological,Extreme temperature,Heat wave,NaN,NaN,...,NaN,NaN,100.000000,1,3218;3226;3242;3251;3261,NaN,"California, Idaho, Nevada, Oregon, Washington ...",United States,United States2021,1
181,2022-0248-IND,2022,248,NaN,Natural,Meteorological,Extreme temperature,Heat wave,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,India,India2022,1
182,2022-0248-PAK,2022,248,NaN,Natural,Meteorological,Extreme temperature,Heat wave,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Pakistan,Pakistan2022,1

In [25]:
hwmap = Timeline()
for i in range(1993, 2022):
        df_all_layer = df_map.loc[df_map['Year']==i]
        map0 = (
        Map()
        .add("", [list(z) for z in zip(df_all_layer['Countryshort'], df_all_layer['times'])], "world",is_map_symbol_show=False)
        .set_series_opts(label_opts=opts.LabelOpts(is_show=False))
        .set_global_opts(
            title_opts=opts.TitleOpts(title="Heatwave Map of Year{}".format(i)),
            visualmap_opts=opts.VisualMapOpts(max_=3,min_=0),
        )
    )
        hwmap.add(map0, "{}Year".format(i))
hwmap.render("map.html")

'/Users/apple/map.html'